- app/config/index.js
- app/lib/ResProvider.js
- docker-compose.yml
some logic added for handling dev env
> config fix

- package-lock.json
- package.json
> release 0.1.1

- README.md
- package-lock.json
- rctmake
Poprawiłam kilka literówek w readme i helpie do `rctmake`.
I zbudowałam `package-lock.json` w nowszej wersji.
> Readme cleanup

- app/application.js
- app/lib/Utils.js
- app/public/components/common/header.js
- app/public/components/common/spinner.js
- app/public/components/common/viewButton.js
- app/public/components/userView/data/dataPanel.js
- app/public/components/userView/data/pager.js
- app/public/components/userView/data/pagesCellsSpecials.js
- app/public/components/userView/data/siteController.js
- app/public/components/userView/data/table/filter.js
- app/public/components/userView/data/table/header.js
- app/public/components/userView/data/table/row.js
- app/public/components/userView/data/table/tablePanel.js
- app/public/components/userView/sidebar/alonePageButton.js
- app/public/components/userView/sidebar/fetchedDataPages.js
- app/public/components/userView/sidebar/multiButtonController.js
- app/public/components/userView/sidebar/sidebar.js
- app/public/model/PrimaryModel.js
- app/public/model/data/FetchedData.js
- app/public/model/data/FetchedDataManager.js
- app/public/styles/custom.css
- app/public/styles/custom/pager.css
- app/public/styles/custom/sidebar.css
- app/public/styles/custom/table.css
- app/public/styles/icons.css
- app/public/styles/images/20/Ellipsis.svg
- app/public/styles/images/20/Filter.svg
- app/public/styles/images/20/Hamburger.svg
- app/public/styles/styles.less
- app/public/utils/csvExport.js
> UI improvement part 2

- package.json
> release 0.1.2

- app/public/components/userView/data/pager.js
- app/public/components/userView/data/table/filter.js
- app/public/styles/custom.css
- app/public/styles/custom/filter/filter.css
- app/public/styles/custom/pager.css
- app/public/styles/styles.less
> UI improvements

- package-lock.json
- package.json
Bump patch version of RCT for release
> [release] 0.1.4

- package-lock.json
- package.json
Release notes:
* Fixed incorrect usage of method for synchronization with Monalisa
* Increased persistence for network errors during synchronization with Bookkeeping and Monalisa
> [release] 0.1.5

- app/lib/database/QueryBuilder.js
- [ x] branch and/or PR name(s) include(s) JIRA ID
- [ x] PR labels are selected
> ORCT-45  filtering bugfix

- rctmake
- in #140 running psql on db container using rctmake was incorrect
> ORCT-130 rctmake bug

- app/lib/database/adapters/PeriodAdapter.js
- app/lib/database/models/typdefs/SequelizePeriod.js
- app/lib/domain/entities/Period.js
- app/lib/services/periods/PeriodService.js
- in period view (enpoint /api/periods)
- field energy renamed to avgEnergy,
- added filed distincEnergies
> [ORCT-128] renaming, added distinc energies to Period

- app/public/components/about/about.js
- app/public/components/detectors/detectorIcon.js
- app/public/styles/custom.less
- app/public/views/flags/overview/flagsContent.js
- app/public/views/flags/overview/flagsTable.js
- app/public/views/runs/runsPerDataPass/overview/content.js
- app/public/views/runs/runsPerDataPass/overview/qcTypeSelection.js
- app/public/views/runs/runsPerPeriod/overview/content.js
- app/public/views/userView/data/detectorSettings/detectorSettings.js
- app/public/views/userView/data/pageSettings/pageSettings.js
- app/public/views/userView/data/table/noSubPageSelected.js
- app/public/views/userView/data/table/tablePanel.js
> Some cleanup 🧹

- app/lib/services/periods/PeriodService.js
- test/lib/server/routes.test.js
> [ORCT-150] - periods endpoint not working after providing pagination

- app/lib/services/periods/PeriodService.js
- add missing field to periods view
> [ORCT-153] - add field year

- app/lib/alimonitor-services/BookkeepingService.js
> amend detectos fetching

- app/lib/alimonitor-services/BookkeepingService.js
- package.json
- mix typo which was causing overflow of logs
- extend npm task `idev`
> amend bkp sync logs

- app/lib/database/repositories/Repository.js
- app/lib/database/repositories/RunRepository.js
- app/lib/server/controllers/dataPass.controller.js
- app/lib/server/controllers/period.controller.js
- app/lib/server/controllers/qualityControl.controller.js
- app/lib/server/controllers/run.controller.js
- app/lib/server/controllers/simulationPass.controller.js
- app/lib/services/dataPasses/DataPassService.js
- app/lib/services/periods/PeriodService.js
- app/lib/services/qualityControl/QualityControlService.js
- app/lib/services/runs/RunService.js
- app/lib/services/simulationPasses/SimulationPassService.js
- app/lib/utils/adaptFindAndCountAllInService.js
- app/lib/utils/index.js
- test/lib/server/routes.test.js
- introduce metod findAndCountAll, and utilize it in services
> [ORCT-167]  find and count all

- database/stored-sql-functionalities/functions/get_run_det_data.sql
- fix bug in `get_run_det_data` sql function
> return correct value for run/det quality

- app/public/styles/rct/custom/components/pager.css
- pager row made stay in place while horizontally scrolling trough the table
> [ORCT-161] Make pager panel sticky

- app/lib/database/migrations/20230904071432-break-with-version-0-3-0.js
- truncate tables due to incorrect data
> Refactor/orct 118/migration due to insert procedures changes

- package-lock.json
- package.json
> @aliceo2/run-condition-table@0.3.0

- .github/workflows/release.yml
- NA
- updates the `release.yml` procedure to re-enable `npm publish` and remove usage of deprecated libraries as per GH recommendation
- NA
> Update release procedure to remove deprecated use

- app/lib/server/utilities/filterParser.js
- test/lib/server/filters.test.js
- NA
- modify filterParser in order to handle logical operator in middle of path 
- NA
> 🐛 Handle middle logical operator

- test/public/periods/overview.test.js
- NA
- increase notoriously failing test timeout
- NA
> increase 'Periods overview - load the page test' timeout

- app/lib/database/utilities/PGQueryBuilder.js
- NA
- use correct default value for offset
- NA
> Use correct default value for offset in legacy endpoints

- app/lib/database/adapters/PeriodAdapter.js
- app/lib/database/models/Period.js
- app/lib/services/periods/PeriodService.js
- NA
- add three fields to `/api/periods`
- runsCount 
- dataPassesCount
- simulationPassesCount
- NA
> [ORCT-162] provide number of existing related data

- app/lib/database/adapters/DataPassAdapter.js
- app/lib/services/dataPasses/DataPassService.js
- NA
- add related data counts to `data pass view` and `anchored to MC view`
- NA
> [ORCT-162] provide number of existing related data for data passes view

- app/lib/utils/ResProvider.js
- NA
- Amend fetching environment vars, ... `'false' is treated as boolean true`
- NA
> Amend variable utilisaition

- app/application.js
- app/config/rct-data/dataAccess/states.js
- app/lib/database/DatabaseService.js
- app/public/Model.js
- app/public/model/DataAccessModel.js
- NA
- Remove unnecessary stuff related to login/logout
- change default state in dataAccessModel to `dataAccess`
- NA
> Login methods cleanup
