app/config/public.js, app/public/components/userView/data/table/header.js, app/public/components/userView/data/table/row.js, app/public/styles/custom.css, app/public/styles/custom/tables/runs.css, app/public/styles/custom/tooltip.css
=> Prettify detector columns and icons

.github/workflows/run-tests.yml, .vscode/settings.json, README.md, docker/dev.env, package-lock.json, rctmake
Builds have the following warning:
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-java@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
https://github.com/actions/checkout/issues/1047 has a bit more information about the warning. The simplest suggestion is to update to v3 of the actions.
=> Fix typos and update github actions to more recent versions

.github/workflows/release.yml
PR which: 
* removes the usage of `set-output` as it is already deprecated and to be removed from GH Action
* removes the usage of 3rd party action `actions/upload-release-asset@v1` as it has been archived and instead use GH cli to replace functionality
=> [OGUI-1369] Update release.yml to remove archived and deprecated usage of GH actions and commands

README.md, docs/GETTING-STARTED.md
Podzieliłam [Readme](https://github.com/AliceO2Group/RunConditionTable/blob/small-refactor/README.md) na rozdziały, część dotyczącą uruchomienia aplikacji wyniosłam do osobnego pliku. Długie i skomplikowane Readme daje wrażenie ogólnego chaosu.
=> Readme cleanup

app/config/public.js, app/lib/database/QueryBuilder.js, app/public/components/common/flagBreadcrumbs.js, app/public/components/userView/data/dataPanel.js, app/public/components/userView/data/flags/flagsTable.js, app/public/components/userView/data/flags/flagsVisualization.js, app/public/components/userView/data/flags/table/flagsTableRow.js, app/public/components/userView/data/pager.js, app/public/components/userView/data/pagesCellsSpecials.js, app/public/components/userView/data/table/indexChip.js, app/public/components/userView/data/table/noDataView.js, app/public/components/userView/data/table/noSubPageSelected.js, app/public/components/userView/data/table/row.js, app/public/components/userView/data/table/tablePanel.js, app/public/components/userView/data/table/title.js, app/public/components/userView/sidebar/sidebar.js, app/public/model/PrimaryModel.js, app/public/model/data/FetchedDataManager.js, app/public/styles/images/icons/15/primary/Back.svg, app/public/styles/images/icons/15/primary/Double Left.svg, app/public/styles/images/icons/15/primary/Double Right.svg, app/public/styles/images/icons/15/primary/Forward.svg, app/public/styles/images/icons/15/primary/More.svg, app/public/styles/images/icons/20/Ellipsis.svg, app/public/styles/images/icons/20/primary/Back.svg, app/public/styles/images/icons/index.css
=> Frontend cleanup 🧹

app/lib/database/procedures/flags.js, app/lib/database/views/flags_view.js, database/design.dbm, database/exported/create-tables.sql, docs/flags/mock.md
No jira issue.
- Missing table renaming
- Cleanup of pgModeler design
=> 🐛 Table name misspelling

app/lib/database/QueryBuilder.js, app/lib/database/index.js, test/database/utilities/QueryBuilder.test.js
- if 'between' clause is incorrectly formatted, backend responds with error
- more tests (QueryBuilder)
=> ORCT-45 - between clause handle incorrect syntax, tests

app/lib/domain/dtos/STDEntity.dto.js, app/lib/domain/dtos/index.js, app/lib/domain/dtos/stdRequest.dto.js, app/lib/server/controllers/ApiDocumentation.controller.js, app/lib/server/controllers/period.controller.js, app/lib/server/controllers/run.controller.js, app/lib/server/routers/index.js, app/lib/server/utilities/controllerWrapper.js, app/lib/server/utilities/dtoValidation.js, app/lib/server/utilities/filterParser.js, app/lib/server/utilities/index.js, app/lib/services/periods/PeriodService.js, app/lib/services/runs/RunService.js, app/lib/utils/obj-utils.js, test/lib/server/filtes.test.js, test/lib/server/index.js
- added possibility to filter fetched data
Example:
Client use url: 
<pre> <code> const URL  = .../?filter[or][field1][gt]=10&filter[or][field1][lt]=3&filter[or][field1][_goperator]=or&filter[or][filed2][like]=LHC_%pass&filter[or][filed2][notLike]=LHC_c%  
</code></pre>
The url will be parsed by qs in express to:  
<pre> <code> const query = {
"filter": {
"or": {
"field1": {
"gt": "10",
"lt": "3",
"_goperator": "or"
},
"filed2": {
"like": "LHC_%pass",
"notLike": "LHC_c%"
}
}
} </code></pre>
query.filter is being passed as an argument to filterToSequelizeWhereClause function
which returns sequelize-compatible where-clause 
<pre><code> const whereClause = {
[Symbol(or)]: {
field1: {
[Symbol(or)]: {
[Symbol(gt)]: '10',
[Symbol(lt)]: '3'
}
},
filed2: { …
=> [ORCT0-134] - filtering for new api

app/lib/server/controllers/run.controller.js, app/lib/server/routers/period.router.js, app/lib/services/runs/RunService.js
- new endpoint `/periods/:id/runs` for listing runs belonging to period, `id` is period id
=> ORCT-135 - add view runsPerPeriod

app/lib/database/adapters/DetectorSubsystemAdapter.js, app/lib/database/adapters/RunAdapter.js, app/lib/database/adapters/index.js, app/lib/database/models/DetectorSubsystem.js, app/lib/database/models/Run.js, app/lib/database/models/index.js, app/lib/database/models/typdefs/SeqeulizeRun.js, app/lib/database/models/typdefs/SequelizeDetectorSubsystem.js, app/lib/database/repositories/RunRepository.js, app/lib/database/repositories/index.js, app/lib/domain/entities/DetectorSubsystem.js, app/lib/domain/entities/Run.js, app/lib/services/runs/RunService.js, package-lock.json, package.json
- runs in runs views have associated detector subsystems
- introduce deepmerge package (https://github.com/TehShrike/deepmerge)
=> [ORCT-135] detectors in run views

app/lib/database/DatabaseManager.js, app/lib/database/repositories/Repository.js, app/lib/database/repositories/index.js, app/lib/server/controllers/run.controller.js, app/lib/server/errors.js, app/lib/server/routers/run.router.js, app/lib/services/runs/RunService.js, app/lib/utils/errors.js, app/lib/utils/index.js, package-lock.json, package.json, test/database/Repository.test.js, test/database/index.js, test/lib/server/routes.test.js
- add endpoint for updating run/detectorSubsystem quality see `api/api-docs`
- add transaction support to repositories
=> [ORCT-140] endpoint for updating quality

app/lib/domain/dtos/stdRequest.dto.js, app/lib/services/dataPasses/DataPassService.js, app/lib/services/periods/PeriodService.js, app/lib/services/qualityControl/QualityControlService.js, app/lib/services/runs/RunService.js
=> [ORCT-145] - add pagination support

app/public/Model.js, app/public/index.js
- fix the bug that forces the `rerequest` on page change (because the first request was not actually being sent)
=> Bind handle location change

.github/dependabot.yml
- [NA] issue has "Fix version" assigned
* Adds dependabot configuration which is a tool automatically checking for:
* new versions for used github-actions
* new versions (minor and major) for NPM dependencies within the project
=> [ORCT-177] Add dependabot auto-checker for dependencies

app/public/views/periods/ActiveColumns/periodsActiveColumns.js, app/public/views/periods/PeriodsModel.js, app/public/views/periods/overview/periodsContent.js, app/public/views/periods/table/periodsTableHeader.js, app/public/views/periods/table/periodsTableRow.js, app/public/views/runs/newRunsPerPeriod/RunsPerPeriodModel.js
- display a `\sqrt(s_{NN})` instead of `Distinct energies`
- add more fields to `periodsActiveFields`
- reduce dependencies for periods view header and row components
=> [ORCT-95] List of energies

app/lib/alimonitor-services/AbstractServiceSynchronizer.js, app/lib/alimonitor-services/BookkeepingService.js, app/lib/alimonitor-services/helpers/Cacher.js, app/lib/utils/http-utils.js, docker/test.env, hooks/pre-commit/newlines.sh, test/lib/alimonitor-services/syncManager.test.js, test/lib/alimonitor-services/testutil/cache-for-test.js, test/lib/index.js
- NA
- fix bug in stopping condition for synchrozniation with Bkp
- add test for synchronization with Bkp (using artifcaly generated data)
- fix bug (spotted thanks to mentioned test) in `makeHttpRequestForJSON` function - there were incorrect logic for catching some fatal errors, what some times have caused app crash
- NA
=> [ORCT-118] bookkeeping services bugfix synchronization tests

app/lib/server/utilities/filterParser.js, test/lib/server/filters.test.js
- NA
- see `app/lib/server/utilities/filterParser.js` changes, method `workaroundForSequlizeBug`
- NA
=> [ORCT-182] add workaround for sequelize misbehaviour

app/lib/server/utilities/filterParser.js, app/lib/utils/ResProvider.js, app/public/components/buttons/dataActionButtons.js, app/public/components/filter/activeFilters.js, app/public/components/filter/filteringPanel.js, app/public/model/OverviewModel.js, app/public/model/filtering/FilterModel.js, app/public/model/navigation/ObsoleteNavigation.js, app/public/utils/filtering/filterUtils.js, app/public/views/flags/overview/flagsContent.js, app/public/views/periods/PeriodsModel.js, app/public/views/periods/overview/periodsContent.js, app/public/views/periods/table/periodsTableRow.js, app/public/views/runs/runsPerDataPass/overview/content.js, app/public/views/runs/runsPerPeriod/overview/content.js, app/public/views/userView/data/table/filtering/obsoleteActiveFilters.js, app/public/views/userView/data/table/filtering/obsoleteFilter.js, app/public/views/userView/data/table/tablePanel.js, test/lib/server/filters.test.js
- hide/show button works with the periods view
- mark the previous `hide` functionality (using the deprecated `dataAccessModel`) as obsolete
-
=> [ORCT-165] Data action buttons

app/lib/alimonitor-services/MonalisaService.js, app/lib/alimonitor-services/MonalisaServiceMC.js, app/lib/alimonitor-services/helpers/ServicesDataCommons.js, rctmake
- NA
- unify usage of regexes to filter data from monalisa
- simplify `rctmake dump:restore`
- NA
=> [ORCT-118] - handling incorrect data in montecarlo

app/lib/database/adapters/SimulationPassAdapter.js, app/lib/services/simulationPasses/SimulationPassService.js
- NA
- add counts of related data for simulation passes views: `runsCount` and `dataPassesCount`
- NA
=> [ORCT-162] provide number of existing related data for simulation passes views

app/public/components/chips/linkChip.js, app/public/views/periods/ActiveColumns/periodsActiveColumns.js
- display number of related data in periods view
- NA
- NA
=> [ORCT-162] utilize data releated counts in periods view
